const CONFIG = {
  BALL_RADIUS: 12,
  PEG_SPACING_BUFFER: 18,
  PEG_SPACING_BUFFER_Y: 15.5,
  PEG_RADIUS: 6,
  PEG_START_FROM: 3,
  BUCKET_HEIGHT: 30,
  GRAVITY_STRENGTH: 0.4,
  FRICTION_STRENGTH: 0.98,
  HISTORY_BUCKET_SIZE: 40,
  HISTORY_BUCKET_SPACING: 4,
};

export default CONFIG;
