export const SERVER_MESSAGES = {
  NEW_PLAYER: "NEW_PLAYER",
  DELETE_PLAYER: "DELETE_PLAYER",
  PLAYERS_DATA: "PLAYERS_DATA",
  PLAYER_DATA: "PLAYER_DATA",

  NEW_MESSAGE: "NEW_MESSAGE",

  BLACKJACK_NEW_PLAYER: "BLACKJACK_NEW_PLAYER",
  BLACKJACK_DELETE_PLAYER: "BLACKJACK_DELETE_PLAYER",
  BLACKJACK_TURN_UPDATE: "BLACKJACK_TURN_UPDATE",
  BLACKJACK_CURRENT_GAME: "BLACKJACK_CURRENT_GAME",
};

export const CLIENT_MESSAGES = {
  PLAYER_MOVE: "PLAYER_MOVE",
  PLAYER_ROTATE: "PLAYER_ROTATE",
  PLAYER_ANIMATION: "PLAYER_ANIMATION",
  UPDATE_NICKNAME: "UPDATE_NICKNAME",

  MESSAGE: "MESSAGE",

  BLACKJACK_MOVE: "BLACKJACK_MOVE",

  // SET_BET: "BLACKJACK_SET_BET",
  // ADD_CARD: "BLACKJACK_ADD_CARD",
};
