export const SERVER_MESSAGES = {
  NEW_PLAYER: "NEW_PLAYER",
  DELETE_PLAYER: "DELETE_PLAYER",
  PLAYERS_DATA: "PLAYERS_DATA",
  PLAYER_DATA: "PLAYER_DATA",

  NEW_MESSAGE: "NEW_MESSAGE",

  BLACKJACK_STATE: "BLACKJACK_STATE",
  BLACKJACK_NEW_PLAYER: "BLACKJACK_NEW_PLAYER",
  BLACKJACK_NEW_GAME: "BLACKJACK_NEW_GAME",
  BLACKJACK_STEP_CHANGE: "BLACKJACK_STEP_CHANGE",
  BLACKJACK_TURN_CHANGE: "BLACKJACK_TURN_CHANGE",
  BLACKJACK_PLAYER_HAND_UPDATE: "BLACKJACK_PLAYER_HAND_UPDATE",
  BLACKJACK_PLAYER_BET_UPDATE: "BLACKJACK_PLAYER_BET_UPDATE",
  BLACKJACK_PLAYER_STATE_UPDATE: "BLACKJACK_PLAYER_STATE_UPDATE",
  BLACKJACK_DEALER_HAND_UPDATE: "BLACKJACK_DEALER_HAND_UPDATE",
  BLACKJACK_END_GAME_RESULTS: "BLACKJACK_END_GAME_RESULTS",
  BLACKJACK_DELETE_PLAYER: "BLACKJACK_DELETE_PLAYER",
  BLACKJACK_BET_ACCEPTED: "BLACKJACK_BET_ACCEPTED",
  BLACKJACK_HIT_ACCEPTED: "BLACKJACK_HIT_ACCEPTED",
  BLACKJACK_STAND_ACCEPTED: "BLACKJACK_STAND_ACCEPTED",
};

export const CLIENT_MESSAGES = {
  PLAYER_MOVE: "PLAYER_MOVE",
  PLAYER_ROTATE: "PLAYER_ROTATE",
  PLAYER_ANIMATION: "PLAYER_ANIMATION",
  UPDATE_NICKNAME: "UPDATE_NICKNAME",

  MESSAGE: "MESSAGE",

  // SET_BET: "BLACKJACK_SET_BET",
  // ADD_CARD: "BLACKJACK_ADD_CARD",

  BLACKJACK_BET: "BLACKJACK_BET",
  BLACKJACK_HIT: "BLACKJACK_HIT",
  BLACKJACK_DOUBLE: "BLACKJACK_DOUBLE",
  BLACKJACK_STAND: "BLACKJACK_STAND",
};
