export const chipNamesMap = {
  chip_black: "chip_black",
  chip_blue: "chip_blue",
  chip_green: "chip_green",
  chip_gray: "chip_gray",
  chip_yellow: "chip_yellow",
  chip_white: "chip_white",
  chip_red: "chip_red",
  chip_pink: "chip_pink",
};

export const chipColorNominalsMap = {
  chip_yellow: 1,
  chip_gray: 2,
  chip_white: 5,
  chip_blue: 10,
  chip_green: 25,
  chip_red: 50,
  chip_black: 100,
  chip_pink: 500,
};

export const cardNamesMap = {
  heart_2: "heart_2",
  heart_3: "heart_3",
  heart_4: "heart_4",
  heart_5: "heart_5",
  heart_6: "heart_6",
  heart_7: "heart_7",
  heart_8: "heart_8",
  heart_9: "heart_9",
  heart_10: "heart_10",
  heart_j: "heart_j",
  heart_q: "heart_q",
  heart_k: "heart_k",
  heart_ace: "heart_ace",

  spade_2: "spade_2",
  spade_3: "spade_3",
  spade_4: "spade_4",
  spade_5: "spade_5",
  spade_6: "spade_6",
  spade_7: "spade_7",
  spade_8: "spade_8",
  spade_9: "spade_9",
  spade_10: "spade_10",
  spade_j: "spade_j",
  spade_q: "spade_q",
  spade_k: "spade_k",
  spade_ace: "spade_ace",

  wine_2: "wine_2",
  wine_3: "wine_3",
  wine_4: "wine_4",
  wine_5: "wine_5",
  wine_6: "wine_6",
  wine_7: "wine_7",
  wine_8: "wine_8",
  wine_9: "wine_9",
  wine_10: "wine_10",
  wine_j: "wine_j",
  wine_q: "wine_q",
  wine_k: "wine_k",
  wine_ace: "wine_ace",

  trefl_2: "trefl_2",
  trefl_3: "trefl_3",
  trefl_4: "trefl_4",
  trefl_5: "trefl_5",
  trefl_6: "trefl_6",
  trefl_7: "trefl_7",
  trefl_8: "trefl_8",
  trefl_9: "trefl_9",
  trefl_10: "trefl_10",
  trefl_j: "trefl_j",
  trefl_q: "trefl_q",
  trefl_k: "trefl_k",
  trefl_ace: "trefl_ace",
};
