/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Blackjack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Blackjack__factory>;
    getContractFactory(
      name: "Casino",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Casino__factory>;
    getContractFactory(
      name: "ICasino",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICasino__factory>;
    getContractFactory(
      name: "Slots",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Slots__factory>;

    getContractAt(
      name: "Blackjack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Blackjack>;
    getContractAt(
      name: "Casino",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Casino>;
    getContractAt(
      name: "ICasino",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICasino>;
    getContractAt(
      name: "Slots",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Slots>;

    deployContract(
      name: "Blackjack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Blackjack>;
    deployContract(
      name: "Casino",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Casino>;
    deployContract(
      name: "ICasino",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICasino>;
    deployContract(
      name: "Slots",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Slots>;

    deployContract(
      name: "Blackjack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Blackjack>;
    deployContract(
      name: "Casino",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Casino>;
    deployContract(
      name: "ICasino",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICasino>;
    deployContract(
      name: "Slots",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Slots>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
